version: '3'
services:
  api:
    container_name: war_ship_api
    image: viktor1233/warshipapi
    ports:
      - "5000:5000"

    environment:
      - FLASK_APP=connection.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    depends_on:
      - db

  db:
    container_name: war_ship_db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=War_ship_game
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: